### ISSUE TITLE
UI broke While Increasing size of icons

### ISSUE THREAD

**Issue by abhayathem** [huacnlee/social-share-button#62]
Hi huacnlee,

First of all thanks for the awesome gem.

I am facing issue while increasing size of icons.
I tried below:
.social-share-button-facebook {
    display: inline-block;
    width: 64px;
    height: 64px;
}
But it broke visiblity of icons. See attached screenshot. Multiple icons started appearing.

Please help me in resolving the issue. I am new to CSS so i might be missing some tricks.

![screen shot 2015-06-03 at 1 06 17 am](https://cloud.githubusercontent.com/assets/7836807/7945183/c1536f54-098c-11e5-94d2-0d8164c5cf4e.png)

**Comment by huacnlee** [comment]
No, it not allow you change the icon size, If you want do that, you need rewrite all stylesheets and use another images.

**Comment by abhayathem** [comment]
Hey huacnlee,

Thanks for reply.
Can you give me an example css with custom image for facebook share icon.
I tried below with custom fb image but it didn't work.
.social-share-button-facebook {
	display: inline-block;
	width: 16px;
	height: 16px;
	background: url("/social/facebook.png") no-repeat;
}
Thanks

**Comment by Javingka** [comment]
This is what I did:

1. search for the images you want to use on internet. In my case I used 36px images 
( https://github.com/Javingka/ror_pinon_03/tree/master/app/assets/images/social-share-button )

2. Include within one of yours css files a css code setting the new size and image to use in your site. 

```css
.social-share-button-facebook {
	display: inline-block;
	width: 36px;
	height: 36px;
	background: image-url("social-share-button/facebook.png") no-repeat;
}
.social-share-button-twitter {
	display: inline-block;
	width: 36px;
	height: 36px;
	background: image-url("social-share-button/twitter.png") no-repeat;

}
.social-share-button-google_plus {
	display: inline-block;
	width: 36px;
	height: 36px;
	background: image-url("social-share-button/google_plus.png") no-repeat;
}
.social-share-button-weibo{
	display: inline-block;
	width: 36px;
	height: 36px;
	background: image-url("social-share-button/weibo.png") no-repeat;
}
.social-share-button-google_bookmark{
	display: inline-block;
	width: 36px;
	height: 36px;
	background: image-url("social-share-button/google_bookmark.png") no-repeat;
}
.social-share-button-delicious{
	display: inline-block;
	width: 36px;
	height: 36px;
	background: image-url("social-share-button/delicious.png") no-repeat;
}
.social-share-button-tumblr{
	display: inline-block;
	width: 36px;
	height: 36px;
	background: image-url("social-share-button/tumblr.png") no-repeat;
}
.social-share-button-plurk{
	display: inline-block;
	width: 36px;
	height: 36px;
	background: image-url("social-share-button/plurk.png") no-repeat;
}
.social-share-button-pinterest{
	display: inline-block;
	width: 36px;
	height: 36px;
	background: image-url("social-share-button/pinterest.png") no-repeat;
}
```
